signer: improve debug reporting of the signer script
In case sighing failure happens, let's not delete temporary files and
let's report the full failed signer invocation command line so that it
is easy to debug the problem.

BRANCH=none
BUG=none
TEST=debugged failure to sign the MP image which happened after
     transitioning into a new sighing environment.

Change-Id: I55accb6887ad00103c9aa7b69aa373f886bce64e
Signed-off-by: Vadim Bendebury <vbendeb@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/1715325
Reviewed-by: Namyoon Woo <namyoon@chromium.org>
Reviewed-by: Mary Ruthven <mruthven@chromium.org>

diff --git a/util/signer/bs b/util/signer/bs
--- a/util/signer/bs
+++ b/util/signer/bs
@@ -16,7 +16,7 @@ progname=$(basename $0)
 OD="/usr/bin/od"
 
 tmpf="/tmp/bs_manifest.$$"
-trap "{ rm -rf [01].flat ${tmpf} ; }" EXIT
+trap "{ if [[ -f 1.flat ]]; then rm -rf [01].flat ${tmpf} ; fi; }" EXIT
 
 usage() {
   local rv="${1}"
@@ -307,9 +307,9 @@ for elf in ${elves[@]}; do
 
   # Make sure output file is not owned by root
   touch "${signed_file}"
-  if ! "${SIGNER}" ${signer_command_params[@]} \
-       -i ${elf} -o "${signed_file}"; then
-    echo "${progname}: ${SIGNER} failed" >&2
+  command="${SIGNER} ${signer_command_params[@]} -i ${elf} -o ${signed_file}"
+  if ! ${command}; then
+    echo "${progname}: \"${command}\" failed" >&2
     exit 1
   fi
 
