signer: allow board id of 0:0:0
In the prod branch the prod signer sets the board id to FFFF:0:10000,
because we're going to start doing automatic signing. We need to be able
to override that board id to 0:0:0. bs doesn't support this right now
because it always assumes the first field of the given board id is a 4
character string that it needs to convert into hex. This change modifies
bs to use 0 for the board_id rlz if the rlz is 0 instead of trying to
convert an ascii character into hex. 0 is the only digit bs will accept
for the board_id, because it's easy to interpret.

BUG=none
BRANCH=cr50
TEST=sign image with CR50_BOARD_ID=0:0:0. Make sure gsctool -b shows the
RLZ is 0 instead of 0x30.

Change-Id: I1fe30877ff8d6d1574934c55c2fb5cdc543c34ad
Signed-off-by: Mary Ruthven <mruthven@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1565549
Reviewed-by: Namyoon Woo <namyoon@chromium.org>

diff --git a/util/signer/bs b/util/signer/bs
--- a/util/signer/bs
+++ b/util/signer/bs
@@ -99,8 +99,15 @@ tweak_manifest () {
     exit 1
   fi
 
-  # Convert board RLZ code from ASCII to hex
-  rlz="0x$(echo -n ${bid_params[0]} | hexdump -ve '/1 "%02x"')"
+  if [[ "${bid_params[0]}" == "0" ]] ; then
+    rlz="0"
+  elif [[ ${#bid_params[0]} == 4 ]] ; then
+    # Convert 4 char board RLZ code from ASCII to hex
+    rlz="0x$(echo -n ${bid_params[0]} | hexdump -ve '/1 "%02x"')"
+  else
+    echo "Invalid RLZ ${bid_params[0]}"
+    exit 1
+  fi
 
   # Prepare text of all three board ID related nodes
   sub="$(printf "\\\n\"board_id\": %s,\\\n" "${rlz}")"
