i2c-pseudo: Add udev rule
This removes the need for servod and iteflash to run as root when run
from outside the chroot.

BRANCH=none
BUG=b:153196340
TEST=ran script outside chroot and confirmed permissions

Change-Id: I4bb9230eb4f581ddb3a095fc5fec0f56c7c573eb
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/2136338
Reviewed-by: Matthew Blecker <matthewb@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Commit-Queue: David Schneider <dnschneid@chromium.org>
Tested-by: David Schneider <dnschneid@chromium.org>

diff --git a/extra/i2c_pseudo/install b/extra/i2c_pseudo/install
--- a/extra/i2c_pseudo/install
+++ b/extra/i2c_pseudo/install
@@ -1,13 +1,21 @@
 #!/bin/sh
 #
 # This attempts to build and install the i2c-pseudo Linux kernel module.
+# Installs a udev rule making i2c-pseudo devices read-write by users in plugdev.
 
 set -e
+cd "$(dirname "$0")"
 
 make clean
 make
 ret=0
 sudo make modules_install || ret="$?"
+
+# Only install udev rule if plugdev group exists.
+if getent group plugdev > /dev/null; then
+  sudo cp -iv 50-i2c-pseudo.rules /etc/udev/rules.d/ \
+    || echo 1>&2 "NOTICE: Failed to copy udev rules file."
+fi
 
 if [ "$ret" -eq 0 ]; then
   make clean
