flash_fp_mcu: Dynamically determine gpiochip number for nocturne
nocturne-kernelnext uses upstream kernel which changes every week.
In this case it's cumbersome to hardcode gpiochip number in the script
and we should determine it dynamically.

Also remove support for unused v4.4 kernel which used spidev32765.0
device instead of spidev1.0.

BUG=b:333509558
TEST=Run `flash_fp_mcu --hello` on nocturne and nocturne-kernelnext

Change-Id: I19b34bfef9a7938108be3fdb6dd0cb10e3121826
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/5439374
Code-Coverage: Zoss <zoss-cl-coverage@prod.google.com>
Reviewed-by: Dawid Niedźwiecki <dawidn@google.com>
Commit-Queue: Patryk Duda <patrykd@google.com>
Tested-by: Patryk Duda <patrykd@google.com>

diff --git a/util/flash_fp_mcu b/util/flash_fp_mcu
--- a/util/flash_fp_mcu
+++ b/util/flash_fp_mcu
@@ -816,20 +816,30 @@ config_nami() {
 }
 
 config_nocturne() {
-  local device="/dev/spidev1.0"
-  # Support kernel version 4.4 during transition to 5.10
-  match_kernel_regex "^4\.4\." && device="/dev/spidev32765.0"
-
   readonly TRANSPORT="SPI"
-  readonly DEVICE="${device}"
+  readonly DEVICE="/dev/spidev1.0"
 
-  readonly GPIO_CHIP="gpiochip360"
-  # FPMCU RST_ODL is on GPP_C10 = 360 + 58 = 418
-  readonly GPIO_NRST=418
-  # FPMCU BOOT0 is on GPP_C8 = 360 + 56 = 416
-  readonly GPIO_BOOT0=416
-  # FP_PWR_EN is on GPP_A11 = 360 + 11 = 371
-  readonly GPIO_PWREN=371
+  # See kernel/v5.4/drivers/pinctrl/intel/pinctrl-sunrisepoint.c
+  # for pin name and pin number.
+
+  local gpiochip_dev_path="pci0000:00/INT344B:00/gpio"
+  local gpiobase
+  if ! gpiobase=$(get_sysfs_gpiochip_base "${gpiochip_dev_path}"); then
+    echo "Unable to find gpio chip base"
+    return "${EXIT_PRECONDITION}"
+  fi
+
+  readonly GPIO_CHIP="gpiochip${gpiobase}"
+
+  # FPMCU RST_ODL is on GPP_C10 = 58
+  local gpionrst=58
+  readonly GPIO_NRST=$(( gpionrst + gpiobase ))
+  # FPMCU BOOT0 is on GPP_C8 = 56
+  local gpioboot=56
+  readonly GPIO_BOOT0=$(( gpioboot + gpiobase ))
+  # FP_PWR_EN is on GPP_A11 = 11
+  local gpiopwren=11
+  readonly GPIO_PWREN=$(( gpiopwren + gpiobase ))
 }
 
 config_strongbad() {
