flash_fp_mcu: add a config for the screebo fingerprint MCU
Screebo is rex family, compared to rex0, only NRST/BOOT0/PWREN has
changed, add a config for Screebo to enable update the fingerprint
MCU firmware features.

BUG=b:278156430
TEST=flash_fp_mcu /opt/google/bios/fw/xxx.bin

Change-Id: Iae897a38f55dbab81822fecc684ecbb5fa2a7919
Signed-off-by: Simon Zhou <zhouguohui@huaqin.corp-partner.google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/4542220
Reviewed-by: Kun Liu <liukun11@huaqin.corp-partner.google.com>
Reviewed-by: Bobby Casey <bobbycasey@google.com>
Reviewed-by: YH Lin <yueherngl@chromium.org>
Reviewed-by: Patryk Duda <patrykd@google.com>

diff --git a/util/flash_fp_mcu b/util/flash_fp_mcu
--- a/util/flash_fp_mcu
+++ b/util/flash_fp_mcu
@@ -704,20 +704,48 @@ config_rex() {
   readonly TRANSPORT="SPI"
   readonly DEVICE="/dev/spidev0.0"
 
-  # See kernel/v5.15/drivers/pinctrl/intel/pinctrl-meteorlake.c
+  # See kernel/v6.1/drivers/pinctrl/intel/pinctrl-meteorlake.c
   # for pin name and pin number.
   # Examine `cat /sys/kernel/debug/pinctrl/INTC1083:00/gpio-ranges` on a
   # rex device to determine gpio number from pin number.
   # For example: GPP_B11, the pin number is 215 from the pinctrl-meteorlake.c.
   # From the gpio-ranges, the gpio value is 925 + (215-204) = 936
 
-  readonly GPIO_CHIP="gpiochip573"
-  # FPMCU RST_ODL is on GPP_C23 = 637 + (52 - 29) = 660
-  readonly GPIO_NRST=660
-  # FPMCU BOOT0 is on GPP_C22 = 637 + (51 - 29) = 659
-  readonly GPIO_BOOT0=659
-  # FP_PWR_EN is on GPP_B11 = 925 + (215-204) = 936
-  readonly GPIO_PWREN=936
+  local gpiochip_dev_path="*/pci0000:00/INTC1083\:00/gpio/*"
+  local gpiobase
+  if ! gpiobase=$(get_sysfs_gpiochip_base "${gpiochip_dev_path}"); then
+    echo "Unable to find gpio chip base"
+    return "${EXIT_PRECONDITION}"
+  fi
+
+  readonly GPIO_CHIP="gpiochip${gpiobase}"
+
+  local model=$(cros_config / name)
+  case "${model}" in
+    screebo)
+      # Screebo is based off Rex but with different pins for FPMCU
+      # FPMCU RST_ODL is on GPP_C21 = 64 + (50 - 29) = 85
+      local gpionrst=85
+      readonly GPIO_NRST=$(( gpionrst + gpiobase ))
+      # FPMCU BOOT0 is on GPP_C20 = 64 + (49 - 29) = 84
+      local gpioboot=84
+      readonly GPIO_BOOT0=$(( gpioboot + gpiobase ))
+      # FP_PWR_EN is on GPP_B08 = 352 + (212-204) - 573 = 360
+      local gpiopwren=360
+      readonly GPIO_PWREN=$(( gpiopwren + gpiobase ))
+      ;;
+    *)
+      # FPMCU RST_ODL is on GPP_C23 = 64 + (52 - 29) = 87
+      local gpionrst=87
+      readonly GPIO_NRST=$(( gpionrst + gpiobase ))
+      # FPMCU BOOT0 is on GPP_C22 = 64 + (51 - 29) = 86
+      local gpioboot=86
+      readonly GPIO_BOOT0=$(( gpioboot + gpiobase ))
+      # FP_PWR_EN is on GPP_B11 = 352 + (215-204) = 363
+      local gpiopwren=363
+      readonly GPIO_PWREN=$(( gpiopwren + gpiobase ))
+      ;;
+  esac
 }
 
 config_zork() {
