flash_ec: Preserve temporary files on failure
Modify the `cleanup` function in flash_ec to preserve temporary files
when the script exits with an error.

Previously, `trap cleanup EXIT` removes all temporary files regardless
of the exit status. If flashing fails in the middle (e.g., during
--no_preserve), valuable artifacts, like partially read images, FMAP
sections, CBI portion, are lost. This makes manual recovery more
difficult.

BUG=b:267804768
TEST=Ran `flash_ec` script but it failed in the middle. Checked the
warning message was printed and the temporary files were preserved.

Change-Id: I4c1d4050463f03974a7af74336833ab3267a7646
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/7005007
Tested-by: Wai-Hong Tam <waihong@google.com>
Code-Coverage: Zoss <zoss-cl-coverage@prod.google.com>
Commit-Queue: Wai-Hong Tam <waihong@google.com>
Reviewed-by: Al Semjonovs <asemjonovs@google.com>

diff --git a/util/flash_ec b/util/flash_ec
--- a/util/flash_ec
+++ b/util/flash_ec
@@ -667,17 +667,37 @@ declare -a DELETE_LIST 	# Array of file/dir names to delete at exit
 # Put back the servo and the system in a clean state at exit
 FROZEN_PIDS=""
 cleanup() {
+	local exit_status=$?
+
 	for pid in ${FROZEN_PIDS}; do
 		info "Sending SIGCONT to process ${pid}!"
 		kill -CONT "${pid}"
 	done
 
 	# Delete all files or directories in DELETE_LIST.
-	for item in "${DELETE_LIST[@]}"; do
-		if [[ -e "${item}" ]]; then
-			print_or_run rm -rf "${item}" &> /dev/null
+	if [[ ${exit_status} -eq 0 ]]; then
+		for item in "${DELETE_LIST[@]}"; do
+			if [[ -e "${item}" ]]; then
+				print_or_run rm -rf "${item}" &> /dev/null
+			fi
+		done
+	else
+		local -a kept_items=()
+
+		for item in "${DELETE_LIST[@]}"; do
+			# Try to remove the item if it's an empty directory.
+			if ! print_or_run rmdir "${item}" &> /dev/null; then
+				kept_items+=("${item}")
+			fi
+		done
+		if [[ ${#kept_items[@]} -gt 0 ]]; then
+			warn "An error occurred. Temporary files were not removed."
+			warn "You may find them in the following locations:"
+			for item in "${kept_items[@]}"; do
+				warn "  ${item}"
+			done
 		fi
-	done
+	fi
 
 	if [ "${CHIP}" = "it83xx" ]; then
 		if [ "${SERVO_TYPE}" = "servo_v2" ]; then
