util/flash_fp_mcu: Power cycle FPMCU on Karis before flashing
Do a complete power cycle instead of only driving VCC1_RST# reset.

BUG=b:320623537
TEST=flash_fp_mcu succeeds on Karis

Change-Id: Id0aaab0f7cbc2a3a18e15432b76b4c8f58cbdba6
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/5322266
Tested-by: Tom Hughes <tomhughes@chromium.org>
Commit-Queue: Tom Hughes <tomhughes@chromium.org>
Reviewed-by: Craig Hesling <hesling@chromium.org>
Code-Coverage: Zoss <zoss-cl-coverage@prod.google.com>

diff --git a/util/flash_fp_mcu b/util/flash_fp_mcu
--- a/util/flash_fp_mcu
+++ b/util/flash_fp_mcu
@@ -252,6 +252,30 @@ power_cycle_fpmcu() {
   fi
 }
 
+# TODO(b/b:320623537): Remove after hardware is fixed.
+power_cycle_fpmcu_workaround() {
+  local gpio_pwren="${1}"
+
+  local model
+  if ! model="$(get_model_name)"; then
+    echo "Failed to get model name."
+    exit "${EXIT_CONFIG}"
+  fi
+
+  if [[ "${model}" == "karis" ]]; then
+    local board_version
+    if ! board_version="$(get_board_version)"; then
+      echo "Failed to get board version."
+      exit "${EXIT_CONFIG}"
+    fi
+
+    if [[ "${board_version}" == "1" ]]; then
+      echo "b/320623537: Running power cycle workaround."
+      power_cycle_fpmcu "${gpio_pwren}"
+    fi
+  fi
+}
+
 # Test the current running kernel version against a regular expression.
 # Returns 0 if the regex matches.
 match_kernel_regex() {
@@ -589,6 +613,9 @@ flash_fp_mcu_board() {
   gpio 1 "${gpio_boot0}"
   gpio 0 "${gpio_nrst}"
   sleep 0.001
+
+  # TODO(b/b:320623537): Remove after hardware is fixed.
+  power_cycle_fpmcu_workaround "${gpio_pwren}"
 
   klog "Binding raw driver"
   if [[ "${transport}" == "UART" ]]; then
