flash_fp_mcu: Dynamically determine gpiochip number for zork
zork-kernelnext uses upstream kernel which changes every week.
In this case it's cumbersome to hardcode gpiochip number in the script
and we should determine it dynamically.

BUG=b:324062803
TEST=Run `flash_fp_mcu --hello` on zork and zork-kernelnext

Change-Id: I5982a3af479d0bb873ad0b80cf4e3a109c4c67cc
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/5273504
Tested-by: Patryk Duda <patrykd@google.com>
Reviewed-by: Tom Hughes <tomhughes@chromium.org>
Commit-Queue: Patryk Duda <patrykd@google.com>
Code-Coverage: Zoss <zoss-cl-coverage@prod.google.com>

diff --git a/util/flash_fp_mcu b/util/flash_fp_mcu
--- a/util/flash_fp_mcu
+++ b/util/flash_fp_mcu
@@ -909,25 +909,24 @@ config_zork() {
   readonly TRANSPORT="UART"
   readonly DEVICE="/dev/ttyS1"
 
-  local gpiochip="gpiochip768"
-  # Support kernel version 5.4 during transition to 5.15+
-  match_kernel_regex "^5\.4\." && gpiochip="gpiochip256"
-  readonly GPIO_CHIP="${gpiochip}"
+  local gpiochip_dev_path="platform/AMD0030:00/gpio"
+  local gpiobase
+  if ! gpiobase=$(get_sysfs_gpiochip_base "${gpiochip_dev_path}"); then
+    echo "Unable to find gpio chip base"
+    return "${EXIT_PRECONDITION}"
+  fi
 
-  local offset=0
-  # Support kernel version 5.4 during transition to 5.15+
-  # v5.4 has GPIOs that are offset by -512
-  match_kernel_regex "^5\.4\." && offset=512
+  local GPIO_CHIP="gpiochip${gpiobase}"
 
-  # FPMCU RST_ODL is on AGPIO 11 = 768 + 11 = 779
-  local gpionrst=779
-  readonly GPIO_NRST=$(( gpionrst - offset ))
-  # FPMCU BOOT0 is on AGPIO 69 = 768 + 69 = 837
-  local gpioboot=837
-  readonly GPIO_BOOT0=$(( gpioboot - offset ))
-  # FPMCU PWR_EN is on AGPIO 32 = 768 + 32 = 800
-  local gpiopwren=800
-  readonly GPIO_PWREN=$(( gpiopwren - offset ))
+  # FPMCU RST_ODL is on AGPIO 11
+  local gpionrst=11
+  readonly GPIO_NRST=$(( gpionrst + gpiobase ))
+  # FPMCU BOOT0 is on AGPIO 69
+  local gpioboot=69
+  readonly GPIO_BOOT0=$(( gpioboot + gpiobase ))
+  # FPMCU PWR_EN is on AGPIO 32
+  local gpiopwren=32
+  readonly GPIO_PWREN=$(( gpiopwren + gpiobase ))
 }
 
 config_guybrush() {
