nuc: Add all IC specific drivers of NPCX5M5G
Add npcx_evb in board folder for testing
Add shared-spi arch support in common layer.

Modified drivers for
1. Fan.c: console command “pwmduty”.
2. Pwm.c: for the issue when set duty to 0.
3. System.c: for hw reset only during system reset.
4. Flash.c: Fixed access denied bug of the flash driver for host command.
5. Comments from Patch Set 1
6. Comments from Patch Set 3 (except sha256.c)
7. Add openocd and flash_ec support for npcx_evb
8. Add little FW and spi-flash upload FW in chip folder
9. Add optional make rules for PROJECT_EXTRA
10.Replace CONFIG_SHRSPI_ARCH with CONFIG_CODERAM_ARCH and remove changes
   in common layer sources for shared-spi arch. (except sysjump)
11.Find the root cause of JTAG issue and use workaround method
   with SUPPORT_JTAG in clock.c
12 Execute hibernate in low power RAM for better power consumption
13 Add workaround method for version console command
14 Modified coding style issues by checkpatch.pl tool

BUG=chrome-os-partner:34346
TEST=make buildall -j; test nuvoton IC specific drivers
BRANCH=none

Change-Id: I5e383420642de1643e2bead837a55c8c58481786
Signed-off-by: Ian Chao <mlchao@nuvoton.com>
Signed-off-by: Randall Spangler <rspangler@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/233742

diff --git a/util/flash_ec b/util/flash_ec
--- a/util/flash_ec
+++ b/util/flash_ec
@@ -64,7 +64,7 @@ BOARDS_STM32=(
 	discovery
 	firefly
 	fruitpie
-	jerry	
+	jerry
 	kitty
 	mighty
 	minimuffin
@@ -90,6 +90,10 @@ BOARDS_STM32_DFU=(
 	dingdong
 	hoho
 	twinkie
+)
+
+BOARDS_NPCX=(
+	npcx_evb
 )
 
 # Flags
@@ -405,6 +409,38 @@ function flash_lm4() {
 	die "Failed to program ${IMG}"
 }
 
+function flash_npcx() {
+	[[ -n "${EC_DIR}" ]] || die "Cannot locate openocd script"
+
+	if [ "${FLAGS_usb}" = ${FLAGS_TRUE} ] ; then
+		OCD_CFG="${BOARD}.cfg"
+	else
+		OCD_CFG="servo_v2.cfg"
+	fi
+
+	OCD_PATH="${EC_DIR}/chip/npcx/openocd"
+	if [ "${FLAGS_unprotect}" = ${FLAGS_TRUE} ] ; then
+		# Unprotect exists, but isn't needed because erasing pstate is
+		# implicit in writing the entire image
+		die "--unprotect not supported for this board."
+	fi
+
+	dut_control jtag_buf_on_flex_en:on
+	dut_control jtag_buf_en:on
+
+	if [ "${FLAGS_ro}" = ${FLAGS_TRUE} ] ; then
+		# Program RO region only
+		OCD_CMDS="init; flash_npcx_ro ${FLAGS_offset}; shutdown;"
+		sudo openocd -s "${OCD_PATH}" -f "${OCD_CFG}" -c "${OCD_CMDS}" || \
+		die "Failed to program ${IMG}"
+	else
+		# Program all EC regions
+		OCD_CMDS="init; flash_npcx_evb ${FLAGS_offset}; shutdown;"
+		sudo openocd -s "${OCD_PATH}" -f "${OCD_CFG}" -c "${OCD_CMDS}" || \
+		die "Failed to program ${IMG}"
+	fi
+}
+
 if dut_control boot_mode 2>/dev/null ; then
 	if [[ "${MCU}" != "ec" ]] ; then
 		die "Toad cable can't support non-ec UARTs"
@@ -434,6 +470,8 @@ elif $(in_array "${BOARDS_STM32_DFU[@]}" "${BOARD}"); then
 	flash_stm32_dfu
 elif [ "${BOARD}" == "link" ]; then
 	flash_link
+elif $(in_array "${BOARDS_NPCX[@]}" "${BOARD}"); then
+	flash_npcx
 else
 	die "board ${BOARD} not supported"
 fi
