flash_fp_mcu: Add skywalker config
Config the gpio used by fingerprint for skywalker.

BUG=b:401396071
TEST=./flash_fp_mcu buccaneer.bin

Change-Id: I50dff20204f9500f522e719b41cc357d1fbe486c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/6332965
Reviewed-by: Ting Shen <phoenixshen@chromium.org>
Code-Coverage: Zoss <zoss-cl-coverage@prod.google.com>
Reviewed-by: Zhengqiao Xia <xiazhengqiao@huaqin.corp-partner.google.com>
Commit-Queue: wen zhang <zhangwen6@huaqin.corp-partner.google.com>
Reviewed-by: Pin-yen Lin <treapking@chromium.org>
Tested-by: wen zhang <zhangwen6@huaqin.corp-partner.google.com>
(cherry picked from commit 4499fb39aaf99c7f1432651104ecded580916385)

diff --git a/util/flash_fp_mcu b/util/flash_fp_mcu
--- a/util/flash_fp_mcu
+++ b/util/flash_fp_mcu
@@ -678,7 +678,8 @@ flash_fp_mcu_board() {
      [[ "${PLATFORM_BASE_NAME}" != "zork" ]] &&
      [[ "${PLATFORM_BASE_NAME}" != "myst" ]] &&
      [[ "${PLATFORM_BASE_NAME}" != "rauru" ]] &&
-     [[ "${PLATFORM_BASE_NAME}" != "skyrim" ]]; then
+     [[ "${PLATFORM_BASE_NAME}" != "skyrim" ]] &&
+     [[ "${PLATFORM_BASE_NAME}" != "skywalker" ]]; then
     gpio in       "${gpio_boot0}" "${gpio_nrst}"
   fi
   gpio unexport "${gpio_boot0}" "${gpio_nrst}"
@@ -1242,6 +1243,27 @@ config_nissa() {
       return "${EXIT_PRECONDITION}"
       ;;
   esac
+}
+
+config_skywalker() {
+  readonly TRANSPORT="SPI"
+  readonly DEVICE="/dev/spidev1.0"
+
+  local dev_path="platform/soc/10005000.pinctrl/gpio"
+  local gpiobase
+  if ! gpiobase=$(get_sysfs_gpiochip_base "${dev_path}"); then
+    echo "Unable to find gpio chip base"
+    return "${EXIT_PRECONDITION}"
+  fi
+
+  readonly GPIO_CHIP="gpiochip${gpiobase}"
+  # FPMCU RST_ODL is $(gpiofind FP_RST_1V8_S3_L) is gpiochip0 134
+  readonly GPIO_NRST=$((gpiobase + $(gpiofind FP_RST_1V8_S3_L|cut -f2 -d" ")))
+  # FPMCU BOOT0 is $(gpiofind AP_FP_FW_UP_STRAP) is gpiochip0 133
+  readonly GPIO_BOOT0=$((gpiobase + $(gpiofind AP_FP_FW_UP_STRAP|cut -f2 -d" ")))
+
+  # EN FP RAILS is $(gpiofind EN_PWR_FP) is gpiochip0 12
+  readonly GPIO_PWREN=$((gpiobase + $(gpiofind EN_PWR_FP|cut -f2 -d" ")))
 }
 
 main() {
