flash_ec: add preserve support for ITE
Update flash_ec script to support reads from ITE based ECs.

BUG=b:295125487
TEST=Program brox over servo V4, verify CBI retained

Change-Id: I5310c4868fd70865a4378afca6cf0020eabf102b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/5245945
Reviewed-by: Wai-Hong Tam <waihong@google.com>
Code-Coverage: Zoss <zoss-cl-coverage@prod.google.com>
Tested-by: Keith Short <keithshort@chromium.org>
Commit-Queue: Keith Short <keithshort@chromium.org>

diff --git a/util/flash_ec b/util/flash_ec
--- a/util/flash_ec
+++ b/util/flash_ec
@@ -1442,7 +1442,10 @@ function ite_dfu_mode() {
 function flash_it83xx() {
 	local TOOL_PATH="${EC_DIR}/build/${BOARD}/util:${PATH}"
 	local ITEFLASH_BIN
+	local TEMP_DIR
 	ITEFLASH_BIN=$(PATH="${TOOL_PATH}" which iteflash)
+	TEMP_DIR="$(mktemp -d --suffix="${TEMP_SUFFIX}")"
+	DELETE_LIST+=("${TEMP_DIR}")
 
 	if [[ ! -x "${ITEFLASH_BIN}" ]]; then
 		die "no iteflash util found."
@@ -1506,6 +1509,17 @@ function flash_it83xx() {
 		if servo_is_ccd; then
 			ITEFLASH_ARGS+=( "--block-write-size=256" )
 		fi
+	fi
+
+	if [[ "${FLAGS_no_preserve}" == "${FLAGS_FALSE}" && \
+	      -z "${FLAGS_read}" ]]; then
+		local IMG_CPY
+
+		IMG_CPY="${TEMP_DIR}/ec.new.cpy.bin"
+		cat "${IMG}" > "${IMG_CPY}"
+		IMG="${IMG_CPY}"
+		preserve_sections "ite_i2c" "${IMG}" "${TEMP_DIR}"    \
+			"${ITEFLASH_ARGS[*]}" || die "${MSG_PROGRAM_FAIL}"
 	fi
 
 	local ERROR_MSG
@@ -1962,7 +1976,6 @@ function read_chip_partially() {
 	local OFFSET
 	local SIZE
 	local FILE_PATH
-	local NPCX_BASE_ADDR
 
 	CHIP_TYPE=${1:?"missing arg 1: Chip type"}
 	CHIP_CMD_PREFIX=${2:?"missing arg 2: Prefix of command"}
@@ -1970,11 +1983,11 @@ function read_chip_partially() {
 	OFFSET=${3:?"missing arg 3: Offset"}
 	SIZE=${4:?"missing arg 4: Size"}
 	FILE_PATH=${5:?"missing arg 5: Image storage path"}
-	NPCX_BASE_ADDR=0x64000000
 
 	if [ "${CHIP_TYPE}" = "npcx_uut" ]; then
-		local UUT_CUR_FMAP_RD
+		local NPCX_BASE_ADDR
 
+		NPCX_BASE_ADDR=0x64000000
 		OFFSET=$(("${NPCX_BASE_ADDR}" + "${OFFSET}"))
 		UUT_CUR_FMAP_RD=( "${CHIP_CMD_PREFIX[@]}" "--opr=rd"  \
 			"--addr=${OFFSET}" "--size=${SIZE}"  \
@@ -1982,6 +1995,42 @@ function read_chip_partially() {
 		echo "${UUT_CUR_FMAP_RD[*]}"
 		print_or_run timeout -k 10 -s 9 "${FLAGS_timeout}" \
 					"${UUT_CUR_FMAP_RD[@]}" || die "${MSG_READ_FAIL}"
+	elif [ "${CHIP_TYPE}" == "ite_i2c" ]; then
+		local UUT_CUR_FMAP_RD
+		local ALIGNED_START SKIP_BYTES ALIGNED_SIZE RANGE ALIGNED_FILE
+
+		# ITE flash tool can start reads on a 256 byte page boundary
+		info "ITE partial read: offset ${OFFSET} size ${SIZE}"
+
+		ALIGNED_START=$((OFFSET & 0xFFFFFF00))
+		SKIP_BYTES=$((OFFSET - ALIGNED_START))
+		ALIGNED_SIZE=$((SIZE + SKIP_BYTES))
+		ALIGNED_FILE="${FILE_PATH}.aligned"
+
+		# --range requires hex representation
+		RANGE=$(printf '0x%x:0x%x' "${ALIGNED_START}" "${ALIGNED_SIZE}" )
+		info "ITE partial read range ${RANGE}"
+
+		UUT_CUR_FMAP_RD=( "${CHIP_CMD_PREFIX[@]}" \
+			"--read=${ALIGNED_FILE}" "--range=${RANGE}")
+		print_or_run timeout -k 10 -s 9 "${FLAGS_timeout}" \
+					"${UUT_CUR_FMAP_RD[@]}" || die "${MSG_READ_FAIL}"
+
+		if [[ "${ALIGNED_START}" != "${OFFSET}" ]]; then
+		   	local DD_CMD
+			# We had to read extra data from the DUT. Use dd
+			# to extract just the portion needed.
+			info "Extract ${SIZE} bytes from temp file"
+			DD_CMD=( "dd" "if=${ALIGNED_FILE}" "of=${FILE_PATH}" \
+				"skip=${SKIP_BYTES}" "count=${SIZE}" "bs=1" )
+			print_or_run "${DD_CMD[@]}"
+		else
+			# Extracted file has what we need
+			print_or_run mv "${ALIGNED_FILE}" "${FILE_PATH}"
+		fi
+
+		# ITE DFU mode must be re-enabled after each operation
+		ite_dfu_mode
 	else
 		die "${MSG_CHIP_READ_INVALID}"
 	fi
@@ -1991,6 +2040,7 @@ function read_chip() {
 	local CHIP_TYPE
 	local CHIP_CMD_PREFIX
 	local FILE_PATH
+	local UUT_CUR_RD
 
 	CHIP_TYPE=${1:?"missing arg 1: Chip type"}
 	CHIP_CMD_PREFIX=${2:?"missing arg 2: Prefix of command"}
@@ -1998,12 +2048,18 @@ function read_chip() {
 	FILE_PATH=${3:?"missing arg 3: Image storage path"}
 
 	if [ "${CHIP_TYPE}" = "npcx_uut" ]; then
-		local UUT_CUR_RD
-
 		UUT_CUR_RD=( "${CHIP_CMD_PREFIX[@]}" "--read-flash" "--file=${FILE_PATH}" )
 		echo "${UUT_CUR_RD[*]}"
 		print_or_run timeout -k 10 -s 9 "${FLAGS_timeout}" \
 					"${UUT_CUR_RD[@]}" || die "${MSG_READ_FAIL}"
+	elif [ "${CHIP_TYPE}" == "ite_i2c" ]; then
+		UUT_CUR_RD=( "${CHIP_CMD_PREFIX[@]}" "--read=${FILE_PATH}" )
+		echo "${UUT_CUR_RD[*]}"
+		print_or_run timeout -k 10 -s 9 "${FLAGS_timeout}" \
+					"${UUT_CUR_RD[@]}" || die "${MSG_READ_FAIL}"
+
+		# ITE DFU mode must be re-enabled after each operation
+		ite_dfu_mode
 	else
 		die "${MSG_CHIP_READ_INVALID}"
 	fi
