helipilot: update flash_fp_mcu script with npcx support
BUG=b:293458644
TEST=flash_fp_mcu using Brya + Quincy
TEST=flash_fp_mcu using Brya + Native FPS (bloonchipper)
TEST=flash_fp_mcu using Nipperkin + Quincy
   NOTE: The UART test on Nipperkin + Quincy is passing
     with a hardware rework b:293458644

Change-Id: I15d9ba2b5439a3ba7ceeb1c7460a77b44fe26338
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/4743661
Reviewed-by: Craig Hesling <hesling@chromium.org>
Reviewed-by: Bobby Casey <bobbycasey@google.com>
Commit-Queue: David Cross <davidmcross@google.com>
Tested-by: David Cross <davidmcross@google.com>
Code-Coverage: Zoss <zoss-cl-coverage@prod.google.com>

diff --git a/util/flash_fp_mcu b/util/flash_fp_mcu
--- a/util/flash_fp_mcu
+++ b/util/flash_fp_mcu
@@ -244,6 +244,24 @@ platform_base_name() {
   echo "${base_name//[0-9]/}"
 }
 
+get_chip() {
+  local board
+  board="$(cros_config /fingerprint board)"
+
+  case "${board}" in
+    bloonchipper|dartmonkey|nocturne_fp|nami_fp)
+      echo "STM32"
+      ;;
+    helipilot)
+      echo "NPCX"
+      ;;
+    *)
+      echo "Error - Unknown board '${board}'." >&2
+      return "${EXIT_CONFIG}"
+      ;;
+  esac
+}
+
 get_default_fw() {
   local board
   board="$(cros_config /fingerprint board)"
@@ -283,30 +301,127 @@ proc_open_file() {
   return "${PIPESTATUS[1]}"
 }
 
+flash_fp_mcu_npcx() {
+  local transport="${1}"
+  local device="${2}"
+  local gpio_nrst="${3}"
+  local file="${4}"
+
+  local cmd_flags=""
+
+  if [[ "${transport}" == "SPI" ]]; then
+    cmd_flags+=" -p linux_spi:dev=${device},spispeed=250k"
+
+    if [[ "${FLAGS_read}" -eq "${FLAGS_TRUE}" ]]; then
+      # Read from FPMCU to file
+      if [[ -e "${file}" ]]; then
+        echo "Output file already exists: ${file}"
+        return "${EXIT_PRECONDITION}"
+      fi
+      echo "# Reading to '${file}' over ${transport}"
+      cmd_flags+=" -r ${file}"
+    else
+      # Write to FPMCU from file
+      if [[ ! -f "${file}" ]]; then
+        echo "Invalid image file: ${file}"
+        return "${EXIT_PRECONDITION}"
+      fi
+      echo "# Flashing '${file}' over ${transport}"
+      cmd_flags+=" -w ${file}"
+    fi
+  elif [[ "${transport}" == "UART" ]]; then
+    local port="${device#/dev/}"
+    cmd_flags+="--port=${port} --baudrate ${FLAGS_baudrate}"
+  fi
+
+  echo "# cmd flags= '${cmd_flags}'"
+
+  local attempt=0
+  local cmd_exit_status=1
+  local cmd=""
+
+  if [[ "${transport}" == "SPI" ]]; then
+    cmd="flashrom ${cmd_flags}"
+  elif [[ "${transport}" == "UART" ]]; then
+    # need to flash monitor first before flashing image over UART
+    cmd="uartupdatetool ${cmd_flags}"
+
+    local cmd_flash_monitor=${cmd}
+    cmd_flash_monitor+=" --opr=wr --addr=0x200c3020"
+
+    #TODO(b/294944527): Make sure this file is available in image
+    cmd_flash_monitor+=" --file /opt/google/biod/fw/npcx_monitor.bin"
+
+    # Reset sequence to enter bootloader mode
+    gpio 0 "${gpio_nrst}"
+    sleep 0.01
+
+    # Release reset as the UART bus is now ready
+    gpio 1 "${gpio_nrst}"
+
+    # Print out the actual underlying command we're running and run it
+    echo "# ${cmd_flash_monitor}"
+    ${cmd_flash_monitor}
+    cmd_exit_status=$?
+
+    if [[ "${cmd_exit_status}" -eq 0 ]]; then
+      echo "# NPCX: Flashing monitor PASSED"
+    else
+      # No point to continue if flashing the monitor failed
+      echo "# NPCX: Flashing monitor FAILED!"
+      return "${EXIT_RUNTIME}"
+    fi
+
+    cmd+=" --auto --offset=0 --file ${file}"
+  fi
+
+  for attempt in $(seq "${FLAGS_retries}"); do
+    # Reset sequence to enter bootloader mode
+    gpio 0 "${gpio_nrst}"
+    sleep 0.01
+
+    # Release reset as the SPI bus is now ready
+    gpio 1 "${gpio_nrst}"
+
+    # Keeping some margin, add delay of 100 ms to consider minimum bootloader
+    # startup time after the reset for npcx devices.
+    sleep 0.1
+
+    # Print out the actual underlying command we're running and run it
+    echo "# ${cmd}"
+    ${cmd}
+    cmd_exit_status=$?
+
+    if [[ "${cmd_exit_status}" -eq 0 ]]; then
+      break
+    fi
+    echo "# Attempt ${attempt} failed."
+    echo
+    sleep 1
+  done
+}
+
 flash_fp_mcu_stm32() {
   local transport="${1}"
   local device="${2}"
   local gpio_nrst="${3}"
-  local gpio_boot0="${4}"
-  local gpio_pwren="${5}"
-  local file="${6}"
-  local deviceid
+  local file="${4}"
 
-  local stm32mon_flags="-p --retries ${STM32MON_CONNECT_RETRIES}"
+  local cmd_flags="-p --retries ${STM32MON_CONNECT_RETRIES}"
 
   if [[ "${transport}" == "UART" ]]; then
-    stm32mon_flags+=" --baudrate ${FLAGS_baudrate} --device ${device}"
+    cmd_flags+=" --baudrate ${FLAGS_baudrate} --device ${device}"
   else
-    stm32mon_flags+=" -s ${device}"
+    cmd_flags+=" -s ${device}"
   fi
 
   if [[ "${FLAGS_hello}" -eq "${FLAGS_FALSE}" ]]; then
     if [[ "${FLAGS_remove_flash_write_protect}" -eq "${FLAGS_TRUE}" ]]; then
-      stm32mon_flags+=" -u"
+      cmd_flags+=" -u"
     fi
 
     if [[ "${FLAGS_remove_flash_read_protect}" -eq "${FLAGS_TRUE}" ]]; then
-      stm32mon_flags+=" -U"
+      cmd_flags+=" -U"
     fi
 
     if [[ "${FLAGS_read}" -eq "${FLAGS_TRUE}" ]]; then
@@ -316,7 +431,7 @@ flash_fp_mcu_stm32() {
         return "${EXIT_PRECONDITION}"
       fi
       echo "# Reading to '${file}' over ${transport}"
-      stm32mon_flags+=" -r ${file}"
+      cmd_flags+=" -r ${file}"
     else
       # Write to FPMCU from file
       if [[ ! -f "${file}" ]]; then
@@ -324,12 +439,58 @@ flash_fp_mcu_stm32() {
         return "${EXIT_PRECONDITION}"
       fi
       echo "# Flashing '${file}' over ${transport}"
-      stm32mon_flags+=" -e -w ${file}"
+      cmd_flags+=" -e -w ${file}"
     fi
   else
     echo "# Saying hello over ${transport}"
   fi
 
+  local attempt=0
+  local cmd_exit_status=1
+  local cmd="stm32mon ${cmd_flags}"
+
+  for attempt in $(seq "${FLAGS_retries}"); do
+    # Reset sequence to enter bootloader mode
+    gpio 0 "${gpio_nrst}"
+    sleep 0.01
+
+    # Release reset as the SPI bus is now ready
+    gpio 1 "${gpio_nrst}"
+
+    # As per section '68: Bootloader timings' from application note below:
+    # https://www.st.com/resource/en/application_note/cd00167594-stm32-microcontroller-system-memory-boot-mode-stmicroelectronics.pdf
+    # bootloader startup time is 16.63 ms for STM32F74xxx/75xxx and 53.975 ms
+    # for STM32H74xxx/75xxx. SPI needs 1 us delay for one SPI byte sending.
+    # Keeping some margin, add delay of 100 ms to consider minimum bootloader
+    # startup time after the reset for stm32 devices.
+    sleep 0.1
+
+    # Print out the actual underlying command we're running and run it
+    echo "# ${cmd}"
+    ${cmd}
+    cmd_exit_status=$?
+
+    if [[ "${cmd_exit_status}" -eq 0 ]]; then
+      break
+    fi
+    echo "# Attempt ${attempt} failed."
+    echo
+    sleep 1
+  done
+}
+
+flash_fp_mcu_board() {
+  local transport="${1}"
+  local device="${2}"
+  local gpio_nrst="${3}"
+  local gpio_boot0="${4}"
+  local gpio_pwren="${5}"
+  local file="${6}"
+  local chip_type="${7}"
+
+  local deviceid=""
+
+  echo "# Flashing '${chip_type}' with '${file}' over ${transport}"
 
   check_hardware_write_protect_disabled
 
@@ -401,38 +562,26 @@ flash_fp_mcu_stm32() {
     return "${EXIT_RUNTIME}"
   fi
 
-  local attempt=0
-  local cmd_exit_status=1
-  local cmd="stm32mon ${stm32mon_flags}"
-
-  for attempt in $(seq "${FLAGS_retries}"); do
-    # Reset sequence to enter bootloader mode
-    gpio 0 "${gpio_nrst}"
-    sleep 0.01
-
-    # Release reset as the SPI bus is now ready
-    gpio 1 "${gpio_nrst}"
-
-    # As per section '68: Bootloader timings' from application note below:
-    # https://www.st.com/resource/en/application_note/cd00167594-stm32-microcontroller-system-memory-boot-mode-stmicroelectronics.pdf
-    # bootloader startup time is 16.63 ms for STM32F74xxx/75xxx and 53.975 ms
-    # for STM32H74xxx/75xxx. SPI needs 1 us delay for one SPI byte sending.
-    # Keeping some margin, add delay of 100 ms to consider minimum bootloader
-    # startup time after the reset for stm32 devices.
-    sleep 0.1
-
-    # Print out the actual underlying command we're running and run it
-    echo "# ${cmd}"
-    ${cmd}
-    cmd_exit_status=$?
-
-    if [[ "${cmd_exit_status}" -eq 0 ]]; then
-      break
-    fi
-    echo "# Attempt ${attempt} failed."
-    echo
-    sleep 1
-  done
+  if [[ "${chip_type}" == "STM32" ]]; then
+    local ret
+    flash_fp_mcu_stm32 \
+      "${transport}"   \
+      "${device}"      \
+      "${gpio_nrst}"   \
+      "${file}"
+    ret=$?
+  elif [[ "${chip_type}" == "NPCX" ]]; then
+    local ret
+    flash_fp_mcu_npcx \
+      "${transport}"   \
+      "${device}"      \
+      "${gpio_nrst}"   \
+      "${file}"
+    ret=$?
+  else
+    echo "# Unsupported chip type found: ${chip_type}"
+    return "${EXIT_CONFIG}"
+  fi
 
   # unload device
   if [[ "${transport}" != "UART" ]]; then
@@ -828,6 +977,7 @@ config_myst() {
 
 main() {
   local filename="$1"
+  local chip_type
 
   # print out canonical path to differentiate between /usr/local/bin and
   # /usr/bin installs
@@ -927,14 +1077,21 @@ main() {
     echo "See b/188985272." >&2
   fi
 
+  if ! chip_type="$(get_chip)"; then
+    echo "Failed to get chip type." >&2
+    exit "${EXIT_CONFIG}"
+  fi
+  echo "Detected chip ${chip_type}."
+
   local ret
-  flash_fp_mcu_stm32 \
+  flash_fp_mcu_board \
     "${TRANSPORT}"   \
     "${DEVICE}"      \
     "${GPIO_NRST}"   \
     "${GPIO_BOOT0}"  \
     "${GPIO_PWREN}"  \
-    "${filename}"
+    "${filename}"    \
+    "${chip_type}"
   ret=$?
 
   if [[ "${FLAGS_services}" -eq "${FLAGS_TRUE}" ]]; then
