flash_fp_mcu: Add config_brox
Add FPMCU flash support for brox

BUG=b:339157568
TEST=On lotso deivce, ran flash_fp_mcu successfully

Change-Id: Iaea2b960a803773d00b3dd79a52f35b77f8b1cf3
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/5563863
Reviewed-by: Tristan Honscheid <honscheid@google.com>
Code-Coverage: Zoss <zoss-cl-coverage@prod.google.com>
Tested-by: wen zhang <zhangwen6@huaqin.corp-partner.google.com>
Commit-Queue: wen zhang <zhangwen6@huaqin.corp-partner.google.com>
Reviewed-by: Siyu Qin <qinsiyu@huaqin.corp-partner.google.com>
Reviewed-by: Karthikeyan Ramasubramanian <kramasub@google.com>

diff --git a/util/flash_fp_mcu b/util/flash_fp_mcu
--- a/util/flash_fp_mcu
+++ b/util/flash_fp_mcu
@@ -1096,6 +1096,39 @@ config_myst() {
   readonly GPIO_PWREN=772
 }
 
+config_brox() {
+  readonly TRANSPORT="SPI"
+  readonly DEVICE="/dev/spidev0.0"
+
+  # Raptorlake uses Alderlake-P PCH and hence
+  # exports INTC1055 ACPI ID matching with tigerlake-pinctrl.c
+  # See kernel/v6.6/drivers/pinctrl/intel/pinctrl-tigerlake.c
+  # for pin name and pin number.
+  # Examine `cat /sys/kernel/debug/pinctrl/INTC1055:00/gpio-ranges` on a
+  # lotso device to determine gpio number from pin number.
+  # For example: GPP_E21, the pin number is 247 from the pinctrl-tigerlake.c.
+  # From the gpio-ranges, the gpio value is 832 + (247-226) = 853
+
+  local gpiochip_dev_path="pci0000:00/INTC1055:00/gpio"
+  local gpiobase
+  if ! gpiobase=$(get_sysfs_gpiochip_base "${gpiochip_dev_path}"); then
+    echo "Unable to find gpio chip base"
+    return "${EXIT_PRECONDITION}"
+  fi
+
+  readonly GPIO_CHIP="gpiochip${gpiobase}"
+
+  # FPMCU RST_ODL is on GPP_E21 = 320 + (247 - 226) = 341
+  local gpionrst=341
+  readonly GPIO_NRST=$(( gpionrst + gpiobase ))
+  # FPMCU BOOT0 is on GPP_D9 = 160 + (108 - 99) = 169
+  local gpioboot=169
+  readonly GPIO_BOOT0=$(( gpioboot + gpiobase ))
+  # FP_PWR_EN is on GPP_E20 = 320 + (246-226) = 340
+  local gpiopwren=340
+  readonly GPIO_PWREN=$(( gpiopwren + gpiobase ))
+}
+
 main() {
   local filename="$1"
   local chip_type
