utils: flash_fp_mcu: Disable SWWP after flashing.
Disable the Software WP after flash NPCX chips. Factory expects SWWP
disabled, when HWWP=0, after running the flash_fp_mcu script.

BUG=b:341193125
TEST=Enable SWWP with "ectool --name=cros_fp flashprotect enable", run
flash_fp_mcu script, and make sure SWWP is disabled with "ectool
--name=cros_fp flashprotect" of Dochi/Omnihnight.

Change-Id: I91297a75251ffa65b0538797df28042709d32bff
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/5604391
Code-Coverage: Zoss <zoss-cl-coverage@prod.google.com>
Reviewed-by: Tom Hughes <tomhughes@chromium.org>
Tested-by: Dawid Niedźwiecki <dawidn@google.com>
Commit-Queue: Dawid Niedźwiecki <dawidn@google.com>

diff --git a/util/flash_fp_mcu b/util/flash_fp_mcu
--- a/util/flash_fp_mcu
+++ b/util/flash_fp_mcu
@@ -715,6 +715,18 @@ flash_fp_mcu_board() {
     klog "Binding cros-ec driver"
     echo "" > "/sys/bus/spi/devices/${deviceid}/driver_override"
     echo "${deviceid}" > /sys/bus/spi/drivers/cros-ec-spi/bind
+
+    # Factory expects SWWP = 0 after flash_fp_mcu, so disable it, see
+    # b/341193125.
+    if [[ "${chip_type}" == "NPCX" ]]; then
+      cmd="ectool --name=cros_fp flashprotect disable"
+      echo "# ${cmd}"
+      ${cmd}
+      cmd_exit_status=$?
+      if [[ "${cmd_exit_status}" -eq 0 ]]; then
+        echo "Failed to disable WP after flashing NPCX."
+      fi
+    fi
   else
     # FPMCU can still have ro_now protection (sector write protection) enabled
     # e.g. when flash_fp_mcu was run with --read option. It is disabled when
