flash_ec: Add boolean sub-command "no_preserve"
This command helps to avoid preserving the sections with preserve
property enabled

BUG=b:267804768
TEST=Flashed on Rex

Change-Id: Icffe0d07f001e99305b14d3728922ce90b0e6c48
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/4602064
Commit-Queue: Madhurima Paruchuri <mparuchuri@google.com>
Reviewed-by: Wai-Hong Tam <waihong@google.com>
Tested-by: Madhurima Paruchuri <mparuchuri@google.com>

diff --git a/util/flash_ec b/util/flash_ec
--- a/util/flash_ec
+++ b/util/flash_ec
@@ -184,6 +184,8 @@ DEFINE_boolean verify "${FLAGS_FALSE}" \
 	"Verify EC firmware image after programming."
 DEFINE_boolean zephyr "${FLAGS_FALSE}" \
 	"Program a Zephyr EC image instead of a CrOS EC image"
+DEFINE_boolean no_preserve "${FLAGS_FALSE}" \
+	"Avoid preserving the sections of firmware image with preserve property"
 
 # Parse command line
 FLAGS_HELP="usage: $0 [flags]"
@@ -1475,8 +1477,6 @@ function flash_npcx_uut() {
 	local EC_UART
 	local TEMP_SUFFIX
 	local TEMP_DIR
-	local CUR_IMG
-	local PRESERVE_STATUS
 	local TOOL_PATH="${EC_DIR}/build/${BOARD}/util:${PATH}"
 	NPCX_UUT=$(PATH="${TOOL_PATH}" which uartupdatetool)
 	EC_UART="$(servo_ec_uart)"
@@ -1587,18 +1587,23 @@ function flash_npcx_uut() {
 			die "Failed to load monitor binary."
 		fi
 
-		PRESERVE_STATUS=0
-		is_preservation_needed "${IMG}" "${TEMP_DIR}" || PRESERVE_STATUS=$?
-		if [[ "${PRESERVE_STATUS}" -eq 0 ]]; then
-			info "Reading current EC firmware image."
-			CUR_IMG="${TEMP_DIR}/ec.cur.bin"
-			local UUT_CUR_RD=( "${NPCX_UUT}" "${UUT_ARGS[@]}"   \
-						"--read-flash" "--file=${CUR_IMG}" )
-			echo "${UUT_CUR_RD[*]}"
-			print_or_run timeout -k 10 -s 9 "${FLAGS_timeout}" \
-				"${UUT_CUR_RD[@]}" || die "${MSG_READ_FAIL}"
+		if [[ "${FLAGS_no_preserve}" == "${FLAGS_FALSE}" ]]; then
+			local CUR_IMG
+			local PRESERVE_STATUS
 
-			preserve_sections "${CUR_IMG}" "${IMG}" "${TEMP_DIR}"
+			PRESERVE_STATUS=0
+			is_preservation_needed "${IMG}" "${TEMP_DIR}" || PRESERVE_STATUS=$?
+			if [[ "${PRESERVE_STATUS}" -eq 0 ]]; then
+				info "Reading current EC firmware image."
+				CUR_IMG="${TEMP_DIR}/ec.cur.bin"
+				local UUT_CUR_RD=( "${NPCX_UUT}" "${UUT_ARGS[@]}"   \
+							"--read-flash" "--file=${CUR_IMG}" )
+				echo "${UUT_CUR_RD[*]}"
+				print_or_run timeout -k 10 -s 9 "${FLAGS_timeout}" \
+					"${UUT_CUR_RD[@]}" || die "${MSG_READ_FAIL}"
+
+				preserve_sections "${CUR_IMG}" "${IMG}" "${TEMP_DIR}"
+			fi
 		fi
 
 		info "Programming EC firmware image."
