util/flash_ec: Add better error message when WP is on
Currently when flashing npcx ECs this tool will fail with "Failed to
load monitor binary" when WP is enabled. This commit adds logic to check
if WP is enabled and give a more informative error message when flashing
fails because of that.

BRANCH=none
BUG=b:210645611
TEST=Ran flash_ec with WP on and verified that the correct error message
is displayed

Signed-off-by: Robert Zieba <robertzieba@google.com>
Change-Id: I08aa69ef3d7bc94fe3958d8d3bc58a967e4902b3
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/3536607
Reviewed-by: Diana Z <dzigterman@chromium.org>

diff --git a/util/flash_ec b/util/flash_ec
--- a/util/flash_ec
+++ b/util/flash_ec
@@ -1496,8 +1496,26 @@ function flash_npcx_uut() {
 		if [[ "${FLAGS_verbose}" = ${FLAGS_TRUE} ]]; then
 			echo "${UUT_MON[*]}"
 		fi
+
+		local monitor_res=0
 		print_or_run timeout -k 10 -s 9 "${FLAGS_timeout}" \
-			"${UUT_MON[@]}" || die "Failed to load monitor binary."
+			"${UUT_MON[@]}" || monitor_res=$?
+
+		if [[ ${monitor_res} != 0 ]]; then
+			# Try to determine if WP is enabled
+			local dut_res=0
+			local wp_state
+			wp_state=$(dut-control fw_wp_state) || dut_res=$?
+
+			if [[ ${dut_res} = 0 ]]; then
+				if echo "${wp_state}" | grep "on"; then
+					die "Failed to load monitor binary, WP is enabled"
+				fi
+			fi
+
+			die "Failed to load monitor binary."
+		fi
+
 
 		info "Programming EC firmware image."
 		local UUT_WR=( "${NPCX_UUT}" "${UUT_ARGS[@]}"      \
