flash_fp_mcu: Abort if raw driver bind fails
This helps simplify the errors being reported.

BRANCH=none
BUG=b:190744837
TEST=# On Hatch and Zork
     scp util/flash_fp_mcu ${DUT_HOSTNAME}:/usr/local/bin/flash_fp_mcu
     ssh ${DUT_HOSTNAME} flash_fp_mcu --hello

Change-Id: I74d57ec0d7fc4bda3fae144fe649124af5c61ba9
Signed-off-by: Craig Hesling <hesling@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/2954919
Reviewed-by: Patryk Duda <patrykd@google.com>
Reviewed-by: Andrew de los Reyes <adlr@chromium.org>

diff --git a/util/flash_fp_mcu b/util/flash_fp_mcu
--- a/util/flash_fp_mcu
+++ b/util/flash_fp_mcu
@@ -334,6 +334,11 @@ flash_fp_mcu_stm32() {
   warn_gpio "${gpio_nrst}" 0 \
     "WARNING: One of the drivers changed NRST pin state on bind attempt."
 
+  if [[ ! -c "${device}" ]]; then
+    echo "Failed to bind raw device driver." >&2
+    return "${EXIT_RUNTIME}"
+  fi
+
   local attempt=0
   local cmd_exit_status=1
   local cmd="stm32mon ${stm32mon_flags}"
