cbi: flash: Preserve CBI section while flashing using flash_ec
BUG=b:267804768
TEST=flashed on Rex, saw the new EC image getting updated

Change-Id: I91d71ab84039254844d217a1eb9c01697cea72ce
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/4493443
Reviewed-by: Wai-Hong Tam <waihong@google.com>
Commit-Queue: Madhurima Paruchuri <mparuchuri@google.com>
Tested-by: Madhurima Paruchuri <mparuchuri@google.com>

diff --git a/util/flash_ec b/util/flash_ec
--- a/util/flash_ec
+++ b/util/flash_ec
@@ -1473,9 +1473,16 @@ function flash_npcx_jtag() {
 function flash_npcx_uut() {
 	local NPCX_UUT
 	local EC_UART
+	local TEMP_SUFFIX
+	local TEMP_DIR
+	local CUR_IMG
+	local PRESERVE_STATUS
 	local TOOL_PATH="${EC_DIR}/build/${BOARD}/util:${PATH}"
 	NPCX_UUT=$(PATH="${TOOL_PATH}" which uartupdatetool)
 	EC_UART="$(servo_ec_uart)"
+	TEMP_SUFFIX=".$(basename "${SCRIPT}").${CHIP}.$$"
+	TEMP_DIR="$(mktemp -d --suffix="${TEMP_SUFFIX}")"
+	DELETE_LIST+=("${TEMP_DIR}")
 
 	# Look for npcx_monitor.bin in multiple directories, starting with
 	# the same path as the EC binary.
@@ -1580,6 +1587,19 @@ function flash_npcx_uut() {
 			die "Failed to load monitor binary."
 		fi
 
+		PRESERVE_STATUS=0
+		is_preservation_needed "${IMG}" "${TEMP_DIR}" || PRESERVE_STATUS=$?
+		if [[ "${PRESERVE_STATUS}" -eq 0 ]]; then
+			info "Reading current EC firmware image."
+			CUR_IMG="${TEMP_DIR}/ec.cur.bin"
+			local UUT_CUR_RD=( "${NPCX_UUT}" "${UUT_ARGS[@]}"   \
+						"--read-flash" "--file=${CUR_IMG}" )
+			echo "${UUT_CUR_RD[*]}"
+			print_or_run timeout -k 10 -s 9 "${FLAGS_timeout}" \
+				"${UUT_CUR_RD[@]}" || die "${MSG_READ_FAIL}"
+
+			preserve_sections "${CUR_IMG}" "${IMG}" "${TEMP_DIR}"
+		fi
 
 		info "Programming EC firmware image."
 		local UUT_WR=( "${NPCX_UUT}" "${UUT_ARGS[@]}"      \
@@ -1594,13 +1614,7 @@ function flash_npcx_uut() {
 		# If it is a program-verify request, then make a temporary
 		# directory to store the image.
 		if [[ "${FLAGS_verify}" == "${FLAGS_TRUE}" ]]; then
-			local TEMP_SUFFIX
-			local TEMP_DIR
-			TEMP_SUFFIX=".$(basename "${SCRIPT}").${CHIP}.$$"
-			TEMP_DIR="$(mktemp -d --suffix="${TEMP_SUFFIX}")"
-
 			IMG_READ="${TEMP_DIR}/ec.read.bin"
-			DELETE_LIST+=( "${TEMP_DIR}" )
 		fi
 	fi
 
@@ -1701,6 +1715,44 @@ fi
 if [ "${NEED_SERVO}" != "no" ] ; then
 	servo_save
 fi
+
+function is_preservation_needed() {
+	local NEW_IMG
+	local TEMP_DIR
+
+	NEW_IMG=${1:?"missing arg 1: EC image path"}
+	NEW_IMG=$(readlink -f "${NEW_IMG}")
+	TEMP_DIR=${2:?"missing arg 2: Temp directory path"}
+
+	(
+		cd "${TEMP_DIR}"
+		dump_fmap "${NEW_IMG}" -e | grep -q ' preserve'
+	)
+}
+
+function preserve_sections() {
+	local CUR_IMG
+	local NEW_IMG
+	local TEMP_DIR
+
+	CUR_IMG=${1:?"missing arg 1: Cur EC image path"}
+	NEW_IMG=${2:?"missing arg 2: New EC image path"}
+	NEW_IMG=$(readlink -f "${NEW_IMG}")
+	TEMP_DIR=${3:?"missing arg 3: Temp directory path"}
+	(
+		cd "${TEMP_DIR}"
+		dump_fmap "${NEW_IMG}" -e | grep ' preserve' | cut \
+			-f1 -d' ' |
+		while read -r line
+		do
+			info "Preserving ${line} section on EC chip"
+			local SEC_IMG="${TEMP_DIR}/ec.cur.${line}.bin"
+
+			cbfstool "${CUR_IMG}" read -r "${line}" -f "${SEC_IMG}"
+			cbfstool "${NEW_IMG}" write -r "${line}" -f "${SEC_IMG}"
+		done
+	)
+}
 
 info "Flashing chip ${CHIP}."
 flash_"${CHIP}"
