flash_ec: Look for npcx_monitor.bin in the same dir as ec.bin
crrev.com/1194646 makes it so chromeos-ec installs the monitor.bin as
part of the build. The script just needs to be updated to use it. This
will allow using flash_ec for downloaded firmware or firmware built
using emerge chromeos-ec.

BUG=b:113288489
BRANCH=none
TEST=emerge-grunt chromeos-ec && flash_ec --board=grunt

Change-Id: Ie92b75a750dbf8ce4e01eafec7a01479915b1270
Signed-off-by: Raul E Rangel <rrangel@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1194354
Reviewed-by: Jett Rink <jettrink@chromium.org>

diff --git a/util/flash_ec b/util/flash_ec
--- a/util/flash_ec
+++ b/util/flash_ec
@@ -1049,6 +1049,16 @@ function flash_npcx_uut() {
 	BUILD_PATH="${EC_DIR}/build/${BOARD}"
 	MONITOR_PATH="${BUILD_PATH}/chip/npcx/spiflashfw"
 	MON="${MONITOR_PATH}/npcx_monitor.bin"
+
+	if [[ ! -f "$MON" ]]; then
+		MON="$(dirname "$IMG")/npcx_monitor.bin"
+	fi
+
+	if [[ ! -f "$MON" ]]; then
+		echo "Failed to find npcx_monitor.bin"
+		exit 1
+	fi
+
 	# The start address to restore monitor firmware binary
 	MON_ADDR="0x200C3020"
 
