flash_fp_mcu: convert tabs to two spaces to match shell style guide
tab2space -unix -t2 board/nocturne_fp/flash_fp_mcu > tmp
mv tmp board/nocturne_fp/flash_fp_mcu
chmod +x board/nocturne_fp/flash_fp_mcu

tab2space -unix -t2 board/nami_fp/flash_fp_mcu > tmp
mv tmp board/nami_fp/flash_fp_mcu
chmod +x board/nami_fp/flash_fp_mcu

BRANCH=nocturne,nami
BUG=none
TEST=flash_fp_mcu /opt/google/biod/fw/nocturne_fp_v2.2.110-b936c0a3c.bin

Change-Id: Ie85aabf3d785a5bb69c4fd36a71dbbd5cc1e966d
Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1444096
Reviewed-by: Nicolas Norvez <norvez@chromium.org>

diff --git a/board/nami_fp/flash_fp_mcu b/board/nami_fp/flash_fp_mcu
--- a/board/nami_fp/flash_fp_mcu
+++ b/board/nami_fp/flash_fp_mcu
@@ -7,31 +7,31 @@
 KBL_GPIOCHIP="gpiochip360"
 
 if [ -e "/sys/class/gpio/${KBL_GPIOCHIP}" ]; then
-	# Ekko configuration
-    	echo "NOTE: For use with updating FP MCU on NAMI boards only"
-	SPIDEV="/dev/spidev32765.0"
-	# GSPI1 ACPI device for FP MCU
-	SPIID="spi-PRP0001:02"
-	# FPMCU RST_ODL is on GPP_C9 = 360 + 57 = 417
-	GPIO_NRST=417
-	# FPMCU BOOT0 is on GPP_D5 = 360 + 77 = 437
-	GPIO_BOOT0=437
-	# FP_PWR_EN is on GPP_B11 = 360 + 35 = 395
-	GPIO_PWREN=395
+  # Ekko configuration
+  echo "NOTE: For use with updating FP MCU on NAMI boards only"
+  SPIDEV="/dev/spidev32765.0"
+  # GSPI1 ACPI device for FP MCU
+  SPIID="spi-PRP0001:02"
+  # FPMCU RST_ODL is on GPP_C9 = 360 + 57 = 417
+  GPIO_NRST=417
+  # FPMCU BOOT0 is on GPP_D5 = 360 + 77 = 437
+  GPIO_BOOT0=437
+  # FP_PWR_EN is on GPP_B11 = 360 + 35 = 395
+  GPIO_PWREN=395
 else
-	echo "Cannot find a known GPIO chip."
-	exit 1
+  echo "Cannot find a known GPIO chip."
+  exit 1
 fi
 
 if [ ! -f "$1" ]; then
-	echo "Invalid image file: $1"
-	echo "Usage: $0 ec.bin"
-	exit 1
+  echo "Invalid image file: $1"
+  echo "Usage: $0 ec.bin"
+  exit 1
 fi
 
 if ectool gpioget EC_WP_L | grep -q '= 0'; then
-	echo "Please make sure WP is deasserted."
-	exit 1
+  echo "Please make sure WP is deasserted."
+  exit 1
 fi
 
 # Ensure the ACPI is not cutting power when unloading cros-ec-spi
diff --git a/board/nocturne_fp/flash_fp_mcu b/board/nocturne_fp/flash_fp_mcu
--- a/board/nocturne_fp/flash_fp_mcu
+++ b/board/nocturne_fp/flash_fp_mcu
@@ -9,43 +9,43 @@ CNL_GPIOCHIP="gpiochip268"
 KBL_GPIOCHIP="gpiochip360"
 
 if [ -e "/sys/class/gpio/${CNL_GPIOCHIP}" ]; then
-	# Meowth configuration
+  # Meowth configuration
 
-	SPIDEV="/dev/spidev1.0"
-	# GSPI1 ACPI device for FP MCU
-	SPIID="spi-PRP0001:01"
-	# FPMCU RST_ODL is on GPP_A23 = 268 + 23 = 291
-	GPIO_NRST=291
-	# FPMCU BOOT0 is on GPP_A21 = 268 + 21 = 289
-	GPIO_BOOT0=289
-	# FP_PWR_EN is on GPP_A11 = 268 + 11 = 279
-	GPIO_PWREN=279
+  SPIDEV="/dev/spidev1.0"
+  # GSPI1 ACPI device for FP MCU
+  SPIID="spi-PRP0001:01"
+  # FPMCU RST_ODL is on GPP_A23 = 268 + 23 = 291
+  GPIO_NRST=291
+  # FPMCU BOOT0 is on GPP_A21 = 268 + 21 = 289
+  GPIO_BOOT0=289
+  # FP_PWR_EN is on GPP_A11 = 268 + 11 = 279
+  GPIO_PWREN=279
 elif [ -e "/sys/class/gpio/${KBL_GPIOCHIP}" ]; then
-	# Nocturne configuration
+  # Nocturne configuration
 
-	SPIDEV="/dev/spidev32765.0"
-	# GSPI1 ACPI device for FP MCU
-	SPIID="spi-PRP0001:02"
-	# FPMCU RST_ODL is on GPP_C10 = 360 + 58 = 418
-	GPIO_NRST=418
-	# FPMCU BOOT0 is on GPP_C8 = 360 + 56 = 416
-	GPIO_BOOT0=416
-	# FP_PWR_EN is on GPP_A11 = 360 + 11 = 371
-	GPIO_PWREN=371
+  SPIDEV="/dev/spidev32765.0"
+  # GSPI1 ACPI device for FP MCU
+  SPIID="spi-PRP0001:02"
+  # FPMCU RST_ODL is on GPP_C10 = 360 + 58 = 418
+  GPIO_NRST=418
+  # FPMCU BOOT0 is on GPP_C8 = 360 + 56 = 416
+  GPIO_BOOT0=416
+  # FP_PWR_EN is on GPP_A11 = 360 + 11 = 371
+  GPIO_PWREN=371
 else
-	echo "Cannot find a known GPIO chip."
-	exit 1
+  echo "Cannot find a known GPIO chip."
+  exit 1
 fi
 
 if [ ! -f "$1" ]; then
-	echo "Invalid image file: $1"
-	echo "Usage: $0 ec.bin"
-	exit 1
+  echo "Invalid image file: $1"
+  echo "Usage: $0 ec.bin"
+  exit 1
 fi
 
 if ectool gpioget EC_WP_L | grep -q '= 0'; then
-	echo "Please make sure WP is deasserted."
-	exit 1
+  echo "Please make sure WP is deasserted."
+  exit 1
 fi
 
 # Ensure the ACPI is not cutting power when unloading cros-ec-spi
